{
 "title": "Daly-BMS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pack SoC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_soc_percent{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pack Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_pack_voltage_volts{job=\"$Job\"} * daly_bms_pack_current_amperes{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pack Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_pack_voltage_volts{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pack Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_pack_current_amperes{job=\"$Job\"}",
     "legendFormat": "Pack Current"
    }
   ]
  },
  {
   "title": "Remain Energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_remaining_capacity_ampere_hours{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remain Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "24.2 * daly_bms_remaining_capacity_ampere_hours{job=\"$Job\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charged Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum_over_time(clamp_min(daly_bms_pack_current_amperes{job=\"$Job\"},0)[${__range}:$__interval])\r\n*\r\n  avg_over_time(daly_bms_pack_voltage_volts{job=\"$Job\"}[${__range}:$__interval])\r\n) / 100000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discharged Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum_over_time(clamp_min(-daly_bms_pack_current_amperes{job=\"$Job\"},0)[${__range}:$__interval])\r\n*\r\n  avg_over_time(daly_bms_pack_voltage_volts{job=\"$Job\"}[${__range}:$__interval])\r\n) / 100000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BMS Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_temperature_celsius{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discharge MOS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_discharge_mos_active{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge MOS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_charge_mos_active{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discharge Cycles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_charge_discharge_cycles_total{job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pack SoC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "daly_bms_soc_percent{job=\"$Job\"}",
     "legendFormat": "Pack SoC"
    }
   ]
  },
  {
   "title": "Pack Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "daly_bms_pack_voltage_volts{job=\"$Job\"}",
     "legendFormat": "Pack Voltage"
    }
   ]
  },
  {
   "title": "Pack Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "daly_bms_pack_current_amperes{job=\"$Job\"}",
     "legendFormat": "Pack Current"
    }
   ]
  },
  {
   "title": "Pack Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "daly_bms_pack_current_amperes{job=\"$Job\"} * daly_bms_pack_voltage_volts{job=\"$Job\"}",
     "legendFormat": "Pack Power"
    }
   ]
  },
  {
   "title": "Cell Voltage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daly_bms_cell_voltage_volts{job=\"$Job\"}",
     "legendFormat": "Cell {{cell}}"
    }
   ]
  },
  {
   "title": "Cell Voltage Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "daly_bms_cell_voltage_delta_volts{job=\"$Job\"}",
     "legendFormat": "Voltage Difference:"
    }
   ]
  }
 ]
}